-include user-settings.inc

haskell_dot_org_ghc=http://haskell.org/ghc/docs/latest/html/libraries
haddock_interfaces=\
  $(haskell_dot_org_ghc)/base,\
  $(haskell_dot_org_ghc)/mtl,

include cabal-make.inc
